_wandb:
    value:
        cli_version: 0.23.1
        e:
            a2va10v1rbpyw8cszsohl708bcvub3a4:
                codePath: src/cookie/train.py
                codePathLocal: src/cookie/train.py
                cpu_count: 8
                cpu_count_logical: 16
                disk:
                    /:
                        total: "1081101176832"
                        used: "28514947072"
                email: s245822@dtu.dk
                executable: /home/elisa/cookie_mlpos/.venv/bin/python3
                git:
                    commit: fdcc29f668a8e7b82b8d3bfd65449b369f54ef15
                    remote: https://github.com/elisabethnielsen/cookie_mlpos.git
                host: elsePC
                memory:
                    total: "12096573440"
                os: Linux-6.6.87.2-microsoft-standard-WSL2-x86_64-with-glibc2.39
                program: /home/elisa/cookie_mlpos/./src/cookie/train.py
                python: CPython 3.12.3
                root: /home/elisa/cookie_mlpos
                startedAt: "2026-01-12T14:31:24.388303Z"
                writerId: a2va10v1rbpyw8cszsohl708bcvub3a4
        m: []
        python_version: 3.12.3
        t:
            "1":
                - 1
            "2":
                - 1
            "3":
                - 16
            "4": 3.12.3
            "5": 0.23.1
            "12": 0.23.1
            "13": linux-x86_64
batch size:
    value: 32
epochs:
    value: 10
lr:
    value: 0.001
